spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: sabalaji
  jpa:
    hibernate:
      ddl-auto:update

server:
  servlet:
    context-path: /hrms/v1
