CREATE SCHEMA hrms;
 
DROP TABLE login;
USE hrms;

CREATE TABLE login
(
 USERID BIGINT AUTO_INCREMENT PRIMARY KEY,
 USERNAME VARCHAR(100) NOT NULL,
 PASSWORD VARCHAR(100) NOT NULL,
 ROLE VARCHAR(100)  NOT NULL
); 

SELECT * 
FROM login;

UPDATE login
SET USER_NAME = 'codegpt1@gmail.com'
WHERE ID= 1;

INSERT INTO login (USERNAME, PASSWORD, ROLE)
VALUES ('test1@codegpt.com', 'code@1', 'admin');

INSERT INTO login (USERNAME, PASSWORD, ROLE)
VALUES ('test2@codegpt.com', 'code@2', 'admin');

 
